### PR TITLE
create c7 file to improve

### PR DESCRIPTION
**Pull request by schomarschomar**
### Description of Change

- Adding a file :+1: 
This fixes #20 
### Test results

- Did you do any localized testing?

###  of course!

/cc: @githubteacher Thischer

### CODE REVIEW

**Comment by rh851** [comment]
Our core product is to be found here:

http://intranet.deutsche-boerse.de/INTRANET/restaurant.nsf/webDocuments/C9152750D0D72F46C12574960047B357

**Comment by rh851** [comment]
> This fixes #20
Didn't you mean #17?

**Review by githubteacher — APPROVED** [review]
👍 Looks good!

**Comment by schomarschomar** [comment]
Merge done

**Pull request merged**
